version: '3'
services:
  db:
#    image: mysql:5.7
    image: mariadb:10.3
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: app_db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "6033:3306"
#    volumes:
#      - ./dump:/docker-entrypoint-initdb.d
  app:
   build: ./
   ports:
     - "3000:3000"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    ports:
      - '8081:80'
